### ISSUE TITLE
The files related to the openEDS2020 dataset are missing

### ISSUE THREAD

**Issue by xingchen77** [dcnieho/Byrneetal_LEyes#1]
Thank you very much for your research, it is very valuable. I would like to learn your relevant code on the openEDS2020 dataset, but I found a few issues, the most important of which is the lack of the pure_EDS2020.tsv file and the test_sampleName_GT.pkl file. Could you please provide these files? I greatly appreciate it.

**Comment by dcnieho** [comment]
Thank you for your interest! I have added the `pure_EDS2020.tsv`, it was an oversight to not include this. I cannot distribute the `test_sampleName_GT.pkl` file since this is part of the EDS2020 dataset, it should have together with the images in their download. Or maybe its available separately from them, i do not remember where i got it.
